### ISSUE TITLE
Delai important au démarage

### ISSUE THREAD

**Issue by Koisell** [nesnes/IA_robot#3]
Bonjour,
Après test sur notre RPi 2 nous avons 26 secondes d'initialisation.
Est-ce normal ? Peut-on améliorer les perfs ?

**Comment by nesnes** [comment]
Je vais y jeter un œil, mais il est possible que ce soit le temps de création du graph du nouveau pathfinding. As-tu localisé la fonction qui prend du temps ?

**Comment by Koisell** [comment]
oui c'est le pathfinding on se demande si on pourrait sérialiser la classe? Et donc pré-calculer tout le match avant les matchs.

**Comment by nesnes** [comment]
Precalculer le match non car l'ordre d'exécution des objectifs est dynamique, mais sauvegarder le graph probablement, j'ai commencé à y réfléchir hier soir.
Je me suis installé un raspberry zéro w pour faire des tests.

**Comment by nesnes** [comment]
J'ai réduit le temps de chargement à 6 secondes sur un vieux raspberry model B. 
Voici comment ça se passe:
- je charge la carte et calcul un hash
- je charge le fichier xml du graph de pathfinding
- si le hash de la carte n'est pas le même de celui stocké dans le fichier du graph, je recalcule le graph et le sauvegarde
- si les hash sont identiques, je recharge le graph depuis le XML chargé

**Comment by nesnes** [comment]
J'ai mesuré 4 secondes sur un raspberry Zero W (1 core, 1 Ghz).
